### ISSUE TITLE
Donde Estas....

### ISSUE THREAD

**Issue by ghost** [linuxserver/Unraid-Dependencies#1]
Buildscript?

**Comment by tobbenb** [comment]
Yes

**Comment by CHBMB** [comment]
@qu4ckth3duck It's not public, and if you read the release thread on the forum you'd realise this is so if Nvidia complain about it, we can pull it, without any issues.

Might I also suggest that you perhaps try and incorporate something you may have heard of in the past called sentences, it really is quite rude to just post one word.

I've been using sentences a long while now, and I have to say, I've found they have helped me communicate with my fellow man, far more effectively and enriched my life in ways I imagine you would find quite liberating.
